version: "2.1"
services:
  qbittorrent:
    image: "linuxserver/qbittorrent"
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK_SET}
      - WEBUI_PORT=${PORT_QBITTORRENT}
    volumes:
      - ${MEDIA_PATH}/config/qbittorrent:/config
      - ${MEDIA_PATH}/downloads:/downloads
      - ${MEDIA_PATH}/scanned:/scanned
      - ${MEDIA_PATH}/scripts:/scripts
      - ${MEDIA_PATH}/torrents:/torrents
      - ${MEDIA_PATH}/logs:/logs
    ports:
      - 6881:6881
      - 6881:6881/udp
      - ${PORT_QBITTORRENT}:${PORT_QBITTORRENT}
    restart: unless-stopped
    # Escape $ with $
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y clamav >> /logs/$$(date +'%d-%m-%Y').log && freshclam >> /logs/$$(date +'%d-%m-%Y').log && /init"]

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK_SET}
    volumes:
      - ${MEDIA_PATH}/config/sonarr:/config
      - ${MEDIA_PATH}/tv:/tv
      - ${MEDIA_PATH}/downloads:/downloads
      - ${MEDIA_PATH}/transcoded/sonarr:/import
    ports:
      - ${PORT_SONARR}:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK_SET}
    volumes:
      - ${MEDIA_PATH}/config/radarr:/config
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/downloads:/downloads
      - ${MEDIA_PATH}/transcoded/radarr:/import
    ports:
      - ${PORT_RADARR}:7878
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA_PATH}/config/jackett:/config
      - ${MEDIA_PATH}/downloads:/downloads
    ports:
      - ${PORT_JACKETT}:9117
    restart: unless-stopped
  
  bazarr:
    image: hotio/bazarr:stable-ffsubsync
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=${UMASK_SET}
    volumes:
      - ${MEDIA_PATH}/config/bazarr:/config
      - ${MEDIA_PATH}/movies:/movies
      - ${MEDIA_PATH}/tv:/tv
      - ${MEDIA_PATH}/logs:/logs
      - ${MEDIA_PATH}/scripts:/scripts
    ports:
      - ${PORT_BAZARR}:6767
    restart: unless-stopped
  
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - UMASK_SET=${UMASK_SET}
    volumes:
      - ${MEDIA_PATH}/config/plex:/config
      - ${MEDIA_PATH}/tv:/tv
      - ${MEDIA_PATH}/movies:/movies
    restart: unless-stopped
  

  
